# Generated by Django 3.1.6 on 2021-02-21 17:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('capacidad', models.IntegerField()),
            ],
            options={
                'verbose_name_plural': 'Buses',
            },
        ),
        migrations.CreateModel(
            name='Chofer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('edad', models.IntegerField()),
            ],
            options={
                'verbose_name_plural': 'Choferes',
            },
        ),
        migrations.CreateModel(
            name='Pasajero',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('identificacion', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Trayecto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('duracion', models.DurationField()),
            ],
        ),
        migrations.CreateModel(
            name='Ruta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disponible', models.BooleanField(default=True)),
                ('salida', models.DateTimeField()),
                ('llegada', models.DateTimeField(blank=True, null=True)),
                ('bus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rutas', to='backend.bus')),
                ('trayecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rutas', to='backend.trayecto')),
            ],
        ),
        migrations.AddField(
            model_name='bus',
            name='chofer',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='backend.chofer'),
        ),
        migrations.CreateModel(
            name='Asiento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.IntegerField(choices=[(1, 'Disponible'), (2, 'Reservado')], default=1)),
                ('identificador', models.IntegerField()),
                ('codigo', models.CharField(max_length=6)),
                ('pasajero', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='backend.pasajero')),
                ('ruta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asientos', to='backend.ruta')),
            ],
        ),
        migrations.AddConstraint(
            model_name='asiento',
            constraint=models.UniqueConstraint(fields=('ruta', 'pasajero'), name='unique-pasajero'),
        ),
    ]
