# Generated by Django 3.1.6 on 2021-02-16 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bus',
            options={'verbose_name_plural': 'Buses'},
        ),
        migrations.RemoveField(
            model_name='bus',
            name='estado',
        ),
        migrations.AlterField(
            model_name='ruta',
            name='llegada',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='Ticket',
        ),
    ]
