# Generated by Django 3.1.6 on 2021-02-16 14:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_auto_20210216_1403'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chofer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('edad', models.IntegerField()),
            ],
            options={
                'verbose_name_plural': 'Choferes',
            },
        ),
        migrations.CreateModel(
            name='Pasajero',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('identificacion', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='asiento',
            name='pasajero',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='backend.pasajero'),
        ),
        migrations.AlterField(
            model_name='bus',
            name='chofer',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='backend.chofer'),
        ),
    ]
