# Generated by Django 3.1.6 on 2021-02-21 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_auto_20210220_1413'),
    ]

    operations = [
        migrations.AddField(
            model_name='asiento',
            name='codigo',
            field=models.CharField(default=25, max_length=6),
            preserve_default=False,
        ),
    ]
