# Generated by Django 3.1.6 on 2021-02-21 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0006_asiento_codigo'),
    ]

    operations = [
        migrations.AddField(
            model_name='ruta',
            name='disponible',
            field=models.BooleanField(default=True),
        ),
    ]
